In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\nice\Desktop\BBI\procurement-ai-assistant\data\Sample_Purchase_Requests.csv")

In [3]:
df

,PR_ID,Requester,Department,Category,Amount_AED,Supplier_Selected,Vendor_ID,Business_Justification,Budget_Code,Required_By_Date,Approval_Level,Quotes_Attached_Count,Status,Missing_Info_Flag,Notes
0,PR-2026-0001,Dina Fathy,Procurement,Software,16849,Future Hardware Co.,VEN-1403,Needed to replace outdated equipment.,NaN,2026-05-23,Manager,0,In Review,Yes,Missing budget code
1,PR-2026-0002,Salma Nabil,Operations,Hardware,29062,Nile Office Supplies,VEN-3018,Supports operational efficiency improvement.,BUD-OP-659,2026-04-02,Department Head,3,Submitted,No,NaN
2,PR-2026-0003,Dina Fathy,HR,Hardware,305544,Future Hardware Co.,VEN-5751,Needed to replace outdated equipment.,BUD-HR-659,2026-03-15,Procurement Committee,3,Draft,No,NaN
3,PR-2026-0004,Mariam Adel,Operations,Cloud Services,60986,ABC Technology Trading LLC,VEN-5643,Required for compliance and service continuity.,BUD-OP-933,2026-04-05,Department Head,2,Draft,Yes,Insufficient quotations
4,PR-2026-0005,Salma Nabil,Marketing,Cloud Services,179176,Future Hardware Co.,VEN-8509,Needed to replace outdated equipment.,BUD-MA-463,2026-03-13,Procurement Committee,3,Draft,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,PR-2026-0076,Youssef Ali,Finance,Training,195957,Mena Consulting Group,VEN-8763,Needed to replace outdated equipment.,BUD-FI-438,2026-02-07,Procurement Committee,2,Returned,Yes,Insufficient quotations
76,PR-2026-0077,Omar Samir,Finance,Cloud Services,12909,Nile Office Supplies,VEN-2551,NaN,BUD-FI-196,2026-02-13,Manager,1,In Review,Yes,Missing business justification
77,PR-2026-0078,Omar Samir,HR,Consulting,190860,NaN,NaN,Needed to replace outdated equipment.,NaN,2026-05-22,Procurement Committee,3,Approved,Yes,Missing budget code; Preferred vendor not prov...
78,PR-2026-0079,Mariam Adel,Finance,Office Supplies,47319,Future Hardware Co.,VEN-4546,Required to support approved project delivery.,BUD-FI-307,2026-03-13,Department Head,2,Submitted,Yes,Insufficient quotations
79,PR-2026-0080,Omar Samir,Marketing,Maintenance,300236,Mena Consulting Group,VEN-8756,NaN,BUD-MA-890,2026-03-04,Procurement Committee,4,Submitted,Yes,Missing business justification

In [4]:
df["Requester"].unique()

array(['Dina Fathy', 'Salma Nabil', 'Mariam Adel', 'Omar Samir',
       'Karim Hassan', 'Youssef Ali'], dtype=object)

In [5]:
df["PR_ID"]

0     PR-2026-0001
1     PR-2026-0002
2     PR-2026-0003
3     PR-2026-0004
4     PR-2026-0005
          ...
75    PR-2026-0076
76    PR-2026-0077
77    PR-2026-0078
78    PR-2026-0079
79    PR-2026-0080
Name: PR_ID, Length: 80, dtype: object

In [6]:
df.head(10)

,PR_ID,Requester,Department,Category,Amount_AED,Supplier_Selected,Vendor_ID,Business_Justification,Budget_Code,Required_By_Date,Approval_Level,Quotes_Attached_Count,Status,Missing_Info_Flag,Notes
0,PR-2026-0001,Dina Fathy,Procurement,Software,16849,Future Hardware Co.,VEN-1403,Needed to replace outdated equipment.,NaN,2026-05-23,Manager,0,In Review,Yes,Missing budget code
1,PR-2026-0002,Salma Nabil,Operations,Hardware,29062,Nile Office Supplies,VEN-3018,Supports operational efficiency improvement.,BUD-OP-659,2026-04-02,Department Head,3,Submitted,No,NaN
2,PR-2026-0003,Dina Fathy,HR,Hardware,305544,Future Hardware Co.,VEN-5751,Needed to replace outdated equipment.,BUD-HR-659,2026-03-15,Procurement Committee,3,Draft,No,NaN
3,PR-2026-0004,Mariam Adel,Operations,Cloud Services,60986,ABC Technology Trading LLC,VEN-5643,Required for compliance and service continuity.,BUD-OP-933,2026-04-05,Department Head,2,Draft,Yes,Insufficient quotations
4,PR-2026-0005,Salma Nabil,Marketing,Cloud Services,179176,Future Hardware Co.,VEN-8509,Needed to replace outdated equipment.,BUD-MA-463,2026-03-13,Procurement Committee,3,Draft,No,NaN
5,PR-2026-0006,Salma Nabil,HR,Consulting,314680,NaN,NaN,Required to support approved project delivery.,BUD-HR-625,2026-02-25,Procurement Committee,2,Returned,Yes,Insufficient quotations; Preferred vendor not ...
6,PR-2026-0007,Dina Fathy,Finance,Maintenance,17462,NaN,NaN,Required to support approved project delivery.,BUD-FI-503,2026-03-26,Manager,1,Approved,Yes,Preferred vendor not provided
7,PR-2026-0008,Omar Samir,Marketing,Office Supplies,278582,Delta Cloud Services,VEN-7615,NaN,BUD-MA-431,2026-02-14,Procurement Committee,4,Draft,Yes,Missing business justification
8,PR-2026-0009,Mariam Adel,IT,Training,161767,NaN,NaN,Needed to replace outdated equipment.,BUD-IT-878,2026-06-01,Procurement Committee,2,Submitted,Yes,Insufficient quotations; Preferred vendor not ...
9,PR-2026-0010,Omar Samir,IT,Office Supplies,18835,Delta Cloud Services,VEN-1482,Required to support approved project delivery.,NaN,2026-02-28,Manager,1,Returned,Yes,Missing budget code

In [7]:
df.loc[10]

PR_ID                                                        PR-2026-0011
Requester                                                    Karim Hassan
Department                                                    Procurement
Category                                                  Office Supplies
Amount_AED                                                         137638
Supplier_Selected                                    Nile Office Supplies
Vendor_ID                                                        VEN-4296
Business_Justification    Required for compliance and service continuity.
Budget_Code                                                    BUD-PR-602
Required_By_Date                                               2026-05-11
Approval_Level                                      Procurement Committee
Quotes_Attached_Count                                                   3
Status                                                          Submitted
Missing_Info_Flag                                                      No
Notes                                                                 NaN
Name: 10, dtype: object

In [8]:
df["Notes"].unique()

array(['Missing budget code', nan, 'Insufficient quotations',
       'Insufficient quotations; Preferred vendor not provided',
       'Preferred vendor not provided', 'Missing business justification',
       'Missing business justification; Preferred vendor not provided',
       'Missing business justification; Insufficient quotations',
       'Missing budget code; Insufficient quotations',
       'Missing business justification; Insufficient quotations; Preferred vendor not provided',
       'Missing budget code; Missing business justification',
       'Missing budget code; Missing business justification; Preferred vendor not provided',
       'Missing budget code; Preferred vendor not provided'], dtype=object)

In [9]:
df["Business_Justification"].value_counts()*100/61

Business_Justification
Needed to replace outdated equipment.              31.147541
Required for compliance and service continuity.    27.868852
Required to support approved project delivery.     24.590164
Supports operational efficiency improvement.       16.393443
Name: count, dtype: float64

In [10]:
df.head(1)

,PR_ID,Requester,Department,Category,Amount_AED,Supplier_Selected,Vendor_ID,Business_Justification,Budget_Code,Required_By_Date,Approval_Level,Quotes_Attached_Count,Status,Missing_Info_Flag,Notes
0,PR-2026-0001,Dina Fathy,Procurement,Software,16849,Future Hardware Co.,VEN-1403,Needed to replace outdated equipment.,NaN,2026-05-23,Manager,0,In Review,Yes,Missing budget code

In [11]:
df.shape

(80, 15)

In [16]:
df.head(10)

,PR_ID,Requester,Department,Category,Amount_AED,Supplier_Selected,Vendor_ID,Business_Justification,Budget_Code,Required_By_Date,Approval_Level,Quotes_Attached_Count,Status,Missing_Info_Flag,Notes
0,PR-2026-0001,Dina Fathy,Procurement,Software,16849,Future Hardware Co.,VEN-1403,Needed to replace outdated equipment.,NaN,2026-05-23,Manager,0,In Review,Yes,Missing budget code
1,PR-2026-0002,Salma Nabil,Operations,Hardware,29062,Nile Office Supplies,VEN-3018,Supports operational efficiency improvement.,BUD-OP-659,2026-04-02,Department Head,3,Submitted,No,NaN
2,PR-2026-0003,Dina Fathy,HR,Hardware,305544,Future Hardware Co.,VEN-5751,Needed to replace outdated equipment.,BUD-HR-659,2026-03-15,Procurement Committee,3,Draft,No,NaN
3,PR-2026-0004,Mariam Adel,Operations,Cloud Services,60986,ABC Technology Trading LLC,VEN-5643,Required for compliance and service continuity.,BUD-OP-933,2026-04-05,Department Head,2,Draft,Yes,Insufficient quotations
4,PR-2026-0005,Salma Nabil,Marketing,Cloud Services,179176,Future Hardware Co.,VEN-8509,Needed to replace outdated equipment.,BUD-MA-463,2026-03-13,Procurement Committee,3,Draft,No,NaN
5,PR-2026-0006,Salma Nabil,HR,Consulting,314680,NaN,NaN,Required to support approved project delivery.,BUD-HR-625,2026-02-25,Procurement Committee,2,Returned,Yes,Insufficient quotations; Preferred vendor not ...
6,PR-2026-0007,Dina Fathy,Finance,Maintenance,17462,NaN,NaN,Required to support approved project delivery.,BUD-FI-503,2026-03-26,Manager,1,Approved,Yes,Preferred vendor not provided
7,PR-2026-0008,Omar Samir,Marketing,Office Supplies,278582,Delta Cloud Services,VEN-7615,NaN,BUD-MA-431,2026-02-14,Procurement Committee,4,Draft,Yes,Missing business justification
8,PR-2026-0009,Mariam Adel,IT,Training,161767,NaN,NaN,Needed to replace outdated equipment.,BUD-IT-878,2026-06-01,Procurement Committee,2,Submitted,Yes,Insufficient quotations; Preferred vendor not ...
9,PR-2026-0010,Omar Samir,IT,Office Supplies,18835,Delta Cloud Services,VEN-1482,Required to support approved project delivery.,NaN,2026-02-28,Manager,1,Returned,Yes,Missing budget code

In [12]:
df.iloc[57]

PR_ID                                                          PR-2026-0058
Requester                                                        Omar Samir
Department                                                       Operations
Category                                                           Training
Amount_AED                                                           319384
Supplier_Selected                                                       NaN
Vendor_ID                                                               NaN
Business_Justification                                                  NaN
Budget_Code                                                      BUD-OP-465
Required_By_Date                                                 2026-02-18
Approval_Level                                        Procurement Committee
Quotes_Attached_Count                                                     3
Status                                                            Submitted
Missing_Info_Flag                                                       Yes
Notes                     Missing business justification; Preferred vend...
Name: 57, dtype: object

In [13]:
def get_all():
    all = []
    for i in range(df.shape[0]):
        all.append(df.iloc[i])
    return all

p = get_all()
print(p[1])

PR_ID                                                     PR-2026-0002
Requester                                                  Salma Nabil
Department                                                  Operations
Category                                                      Hardware
Amount_AED                                                       29062
Supplier_Selected                                 Nile Office Supplies
Vendor_ID                                                     VEN-3018
Business_Justification    Supports operational efficiency improvement.
Budget_Code                                                 BUD-OP-659
Required_By_Date                                            2026-04-02
Approval_Level                                         Department Head
Quotes_Attached_Count                                                3
Status                                                       Submitted
Missing_Info_Flag                                                   No
Notes                                                              NaN
Name: 1, dtype: object

In [14]:
df["Amount_AED"].max()

348957

In [15]:
df.loc[df["Amount_AED"]>200000]

,PR_ID,Requester,Department,Category,Amount_AED,Supplier_Selected,Vendor_ID,Business_Justification,Budget_Code,Required_By_Date,Approval_Level,Quotes_Attached_Count,Status,Missing_Info_Flag,Notes
2,PR-2026-0003,Dina Fathy,HR,Hardware,305544,Future Hardware Co.,VEN-5751,Needed to replace outdated equipment.,BUD-HR-659,2026-03-15,Procurement Committee,3,Draft,No,NaN
5,PR-2026-0006,Salma Nabil,HR,Consulting,314680,NaN,NaN,Required to support approved project delivery.,BUD-HR-625,2026-02-25,Procurement Committee,2,Returned,Yes,Insufficient quotations; Preferred vendor not ...
7,PR-2026-0008,Omar Samir,Marketing,Office Supplies,278582,Delta Cloud Services,VEN-7615,NaN,BUD-MA-431,2026-02-14,Procurement Committee,4,Draft,Yes,Missing business justification
15,PR-2026-0016,Youssef Ali,Procurement,Office Supplies,245962,Delta Cloud Services,VEN-8716,NaN,BUD-PR-158,2026-03-11,Procurement Committee,1,Draft,Yes,Missing business justification; Insufficient q...
19,PR-2026-0020,Dina Fathy,IT,Office Supplies,272075,Mena Consulting Group,VEN-7993,Required for compliance and service continuity.,NaN,2026-04-17,Procurement Committee,2,Submitted,Yes,Missing budget code; Insufficient quotations
21,PR-2026-0022,Mariam Adel,IT,Maintenance,299329,ABC Technology Trading LLC,VEN-3076,Required to support approved project delivery.,BUD-IT-355,2026-04-03,Procurement Committee,1,Submitted,Yes,Insufficient quotations
27,PR-2026-0028,Omar Samir,Finance,Software,235460,Future Hardware Co.,VEN-4547,NaN,BUD-FI-126,2026-05-13,Procurement Committee,3,Draft,Yes,Missing business justification
32,PR-2026-0033,Dina Fathy,Finance,Software,324775,Mena Consulting Group,VEN-3084,Supports operational efficiency improvement.,BUD-FI-884,2026-03-07,Procurement Committee,3,Submitted,No,NaN
36,PR-2026-0037,Omar Samir,Finance,Training,343899,Delta Cloud Services,VEN-3458,Supports operational efficiency improvement.,BUD-FI-264,2026-04-22,Procurement Committee,1,Draft,Yes,Insufficient quotations
38,PR-2026-0039,Youssef Ali,Procurement,Office Supplies,348118,NaN,NaN,NaN,BUD-PR-528,2026-05-19,Procurement Committee,1,Draft,Yes,Missing business justification; Insufficient q...
46,PR-2026-0047,Omar Samir,IT,Hardware,305925,ABC Technology Trading LLC,VEN-8185,Required for compliance and service continuity.,BUD-IT-478,2026-02-28,Procurement Committee,3,In Review,No,NaN
53,PR-2026-0054,Mariam Adel,Marketing,Maintenance,259502,ABC Technology Trading LLC,VEN-9540,Required to support approved project delivery.,BUD-MA-422,2026-03-18,Procurement Committee,3,Submitted,No,NaN
57,PR-2026-0058,Omar Samir,Operations,Training,319384,NaN,NaN,NaN,BUD-OP-465,2026-02-18,Procurement Committee,3,Submitted,Yes,Missing business justification; Preferred vend...
63,PR-2026-0064,Omar Samir,Operations,Maintenance,346378,NaN,NaN,Needed to replace outdated equipment.,BUD-OP-920,2026-03-30,Procurement Committee,3,Submitted,Yes,Preferred vendor not provided
71,PR-2026-0072,Youssef Ali,Operations,Maintenance,273804,ABC Technology Trading LLC,VEN-9188,NaN,BUD-OP-314,2026-03-18,Procurement Committee,3,Submitted,Yes,Missing business justification
72,PR-2026-0073,Mariam Adel,Marketing,Software,231035,ABC Technology Trading LLC,VEN-3655,Required for compliance and service continuity.,BUD-MA-179,2026-04-13,Procurement Committee,2,Draft,Yes,Insufficient quotations
74,PR-2026-0075,Karim Hassan,Marketing,Consulting,348957,Future Hardware Co.,VEN-5754,NaN,BUD-MA-480,2026-04-13,Procurement Committee,2,Submitted,Yes,Missing business justification; Insufficient q...
79,PR-2026-0080,Omar Samir,Marketing,Maintenance,300236,Mena Consulting Group,VEN-8756,NaN,BUD-MA-890,2026-03-04,Procurement Committee,4,Submitted,Yes,Missing business justification